// グローバルスタイル（テーマ・OnchainKit・共通 CSS）
import '@coinbase/onchainkit/styles.css';
import type { Metadata, Viewport } from 'next';
import './../css/globals.css';
import './../css/theme.css';
import { Providers } from './providers';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

/**
 * メタデータを生成するメソッド
 * @returns
 */
export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_URL;
  return {
    title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
    description: 'Generated by `create-onchain --mini`, a Next.js template for MiniKit',
    other: {
      // Farcaster Frame 用のメタデータをヘッダに埋め込み
      'fc:frame': JSON.stringify({
        version: 'next',
        imageUrl: process.env.NEXT_PUBLIC_APP_HERO_IMAGE,
        button: {
          title: `Launch ${process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME}`,
          action: {
            type: 'launch_frame',
            name: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
            url: URL,
            splashImageUrl: process.env.NEXT_PUBLIC_SPLASH_IMAGE,
            splashBackgroundColor: process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR,
          },
        },
      }),
    },
  };
}

/**
 * ルートレイアウトコンポーネント
 * @param param0
 * @returns
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        {/* MiniKitProvider 等でアプリ全体をラップ */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
