name: CI

on:
  push:
    branches: [complete]
  pull_request:
    branches: [complete]

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Check Prettier formatting
        run: pnpm prettier --check .

  type-check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript compiler check
        run: pnpm tsc --noEmit

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint-and-format, type-check]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build
        env:
          # ビルド時に必要な環境変数（必要に応じて追加）
          NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL || 'http://localhost:3000' }}
          NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME: ${{ secrets.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME }}
          NEXT_PUBLIC_APP_SUBTITLE: ${{ secrets.NEXT_PUBLIC_APP_SUBTITLE }}
          NEXT_PUBLIC_APP_DESCRIPTION: ${{ secrets.NEXT_PUBLIC_APP_DESCRIPTION }}
          NEXT_PUBLIC_APP_ICON: ${{ secrets.NEXT_PUBLIC_APP_ICON }}
          NEXT_PUBLIC_APP_SPLASH_IMAGE: ${{ secrets.NEXT_PUBLIC_APP_SPLASH_IMAGE }}
          NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR: ${{ secrets.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR }}
          NEXT_PUBLIC_APP_PRIMARY_CATEGORY: ${{ secrets.NEXT_PUBLIC_APP_PRIMARY_CATEGORY }}
          NEXT_PUBLIC_APP_HERO_IMAGE: ${{ secrets.NEXT_PUBLIC_APP_HERO_IMAGE }}
          NEXT_PUBLIC_APP_TAGLINE: ${{ secrets.NEXT_PUBLIC_APP_TAGLINE }}
          NEXT_PUBLIC_APP_OG_TITLE: ${{ secrets.NEXT_PUBLIC_APP_OG_TITLE }}
          NEXT_PUBLIC_APP_OG_DESCRIPTION: ${{ secrets.NEXT_PUBLIC_APP_OG_DESCRIPTION }}
          NEXT_PUBLIC_APP_OG_IMAGE: ${{ secrets.NEXT_PUBLIC_APP_OG_IMAGE }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            .next/
            public/
          retention-days: 7

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate
